#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-lang3
Version  : 3.4
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
Source0  : https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
Source1  : https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom
Source2  : https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.pom
Source3  : https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
Source4  : https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-commons-lang3-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-lang3 package.
Group: Data

%description data
data components for the mvn-commons-lang3 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.8.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.8.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.8.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.8.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom
/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.pom
/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
/usr/share/java/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.pom
